---
- name: Delete PyYAML
  shell: "{{ item }}"
  loop:
    - "rm -rf {{ fts_venv }}/lib/python3.11/site-packages/yaml"
    - "rm -rf {{ fts_venv }}/lib/python3.11/site-packages/PyYAML-*"

- name: Install apt packages
  apt:
    name: "{{ fts_ui_apt_packages }}"

- name: "Install pip packages"
  ansible.builtin.pip:
    name: "{{ fts_ui_pip_packages }}"
    virtualenv: "{{ fts_venv }}"
    virtualenv_command: "{{ venv_python }} -m venv"

- name: "Install {{ fts_ui_pip_package_name }}"
  ansible.builtin.pip:
    name: "{{ fts_ui_pip_package_name }}"
    virtualenv: "{{ fts_venv }}"
    virtualenv_command: "{{ venv_python }} -m venv"
