---
- name: Stop service
  service:
    name: "{{ fts_ui_service_name }}"
    state: stopped
  ignore_errors: true

- name: Remove unit file
  file:
    path: "{{ unit_files_location }}/{{ fts_ui_service_name }}.service"
    state: absent

- name: Uninstall
  ansible.builtin.pip:
    name: "{{ fts_ui_pip_package_name }}"
    state: absent
    virtualenv: "{{ fts_venv }}"
    virtualenv_command: "{{ venv_python }} -m venv"
