---
videoserver_package_location: "/tmp/{{ videoserver_package }}"
videoserver_config_location: "/opt/{{ videoserver_config_file }}"
videoserver_executable_location: "/usr/local/bin/{{ videoserver_executable }}"
