---
# system information
murmur_ipv4: 0.0.0.0
murmur_port: 64738

murmur_service_name: mumble-server

# Set initial service state. Recommended values: `started` or `stopped`.
murmur_state: started

# Enable service. Recommended values: `true` or `false`
murmur_enabled: true
