---
#NodeRed username
nodered_username: "admin"

#NodeRed password
nodered_password: "password"

# When Node-RED has a flow that connects to an RTSP server, set to true
nodered_wait_for_videoserver: false

# Max seconds Node-RED Server will wait to connect to Video Server
nodered_wait_for_videoserver_timeout: 600

# generate a random token
noderedserver_token: "{{ lookup('password', '/dev/null chars=ascii,digits length=16') }}"

#Location of the NodeRed installation path
nodered_install_folder: "/root/.node-red"

#Location of the NodeRed settings file
nodered_settings_file: "settings.js"

# system information
noderedserver_ipv4: 0.0.0.0

nodered_npm_packages:
  - node-red
  - node-red-admin
  - node-red-contrib-web-worldmap

nodered_nodes:
  - node-red-contrib-config
  - node-red-dashboard
  - node-red-contrib-credentials

nodered_flows:
  - salute.json
  - videochecker.json
  - webmap.json

nodered_post_flows_body: "{{ lookup('template', 'flows.json.j2') }}"

nodered_service_name: nodered

# Set initial service state. Recommended values: `started` or `stopped`.
nodered_state: started

# Enable service.
nodered_enabled: true
