---
- name: "Include {{ ansible_distribution }}-specific variables"
  include_vars: "{{ ansible_distribution }}.yml"

- name: Get public IPv4
  uri:
    url: http://ifconfig.me/ip
    return_content: yes
  register: ip_response

- name: Set public IPv4
  set_fact:
    videoserver_public_ipv4: "{{ ip_response.content }}"

- name: Print IPv4
  debug:
    msg: "videoserver_public_ipv4 = {{ videoserver_public_ipv4 }}"

- name: Set localhost IPv4
  set_fact:
    videoserver_ipv4: 127.0.0.1

  # ansible_archtecture mappings:
  # x86_64: amd64
  # ppc64le: ppc64el
  # s390x: s390x
  # armv7l: armhf
  # aarch64: arm64

- name: "Include {{ ansible_architecture }}-specific variables"
  include_vars: "{{ ansible_architecture }}.yml"

- name: Setup
  include_tasks: "setup-{{ ansible_distribution }}.yml"

- name: Configure
  include_tasks: "configure-{{ ansible_distribution }}.yml"

- name: Notify handlers to print at the end
  shell: ":"
  notify:
    - print videoserver url
