---
- name: Ensure nodered group exists
  group:
    name: nodered
    state: present

- name: Ensure nodered user is in nodered group
  user:
    name: nodered
    group: nodered

- name: Template unit file
  template:
    src: nodered.service.j2
    dest: "{{ unit_files_location }}/{{ nodered_service_name }}.service"
    owner: root
    group: root
    mode: 0644

- name: Kill any currently running processes
  include_tasks: ../../common/tasks/kill.yml
  vars:
    process: "node-red"

- name: Enable service
  service:
    name: "{{ nodered_service_name }}"
    enabled: true
    use: systemd
  register: enable_nodered_state
  retries: 5
  until: enable_nodered_state is success

- name: Set service state
  service:
    name: "{{ nodered_service_name }}"
    state: "restarted"
    use: systemd
  register: set_nodered_state
  retries: 5
  until:
    - set_nodered_state is success
    - set_nodered_state.status.ActiveState == "active"

- name: Import Node-RED flows
  block:
    - name: Wait until Node-RED import port is open
      wait_for:
        port: 1880

    - name: Import Node-RED flows via HTTP POST
      uri:
        url: "http://{{ noderedserver_ipv4 }}:1880/flows"
        method: POST
        headers:
          Content-Type: application/json
          Node-RED-API-Version: v1
          Node-RED-Deployment-Type: full
        body: "{{ nodered_post_flows_body }}"
        body_format: json
        status_code: 204

- name: Ensure reachable connection to Video Server
  block:
    - name: Wait for Video Server to be available
      wait_for:
        host: "{{ videoserver_ipv4 }}"
        port: 9997
        timeout: "{{ nodered_wait_for_videoserver_timeout | int }}"

    - name: Reload Node-RED flows
      uri:
        url: "http://{{ noderedserver_ipv4 }}:1880/flows"
        method: POST
        headers:
          Content-Type: application/json
          Node-RED-Deployment-Type: reload
          Node-RED-API-Version: v1
        body:
          flows: [{}]
        body_format: json
        status_code: 204

  when: nodered_wait_for_videoserver
