---
# system information
mumble_web_ipv4: "0.0.0.0"

mumble_web_npm_packages:
  - mumble-web

mumble_web_service_name: mumble-web

# Set initial service state. Recommended values: `started` or `stopped`.
mumble_web_state: started

# Enable service.
mumble_web_enabled: true
