---
- name: "Include {{ ansible_distribution }}-specific variables"
  include_vars: "{{ ansible_distribution }}.yml"

- name: Get public IPv4
  uri:
    url: http://ifconfig.me/ip
    return_content: yes
  register: ip_response

- name: Set public IPv4
  set_fact:
    murmur_ipv4: "{{ ip_response.content }}"

- name: Print IPv4
  debug:
    msg: "murmur_ipv4 = {{ murmur_ipv4 }}"

- name: Setup
  include_tasks: "setup-{{ ansible_distribution }}.yml"

- name: Configure
  include_tasks: "configure-{{ ansible_distribution }}.yml"

- name: Notify handlers
  shell: ":"
  notify:
    - print murmur ip
    - print murmur credentials
    - print reconfigure message
