name: fts
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - ca-certificates=2022.4.26=h06a4308_0
  - certifi=2021.10.8=py38h06a4308_2
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - ncurses=6.3=h7f8727e_2
  - openssl=1.1.1n=h7f8727e_0
  - pip=21.2.4=py38h06a4308_0
  - python=3.8.13=h12debd9_0
  - readline=8.1.2=h7f8727e_1
  - setuptools=61.2.0=py38h06a4308_0
  - sqlite=3.38.2=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - unzip=6.0=h611a1e1_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - pip:
    - alembic==1.7.7
    - bcrypt==3.1.7
    - cffi==1.15.0
    - charset-normalizer==2.0.12
    - click==8.0.4
    - colorama==0.4.4
    - cryptography==36.0.2
    - defusedxml==0.7.1
    - dnspython==1.16.0
    - email-validator==1.2.1
    - eventlet==0.29.0
    - flask==1.1.2
    - flask-cors==3.0.9
    - flask-httpauth==4.2.0
    - flask-login==0.5.0
    - flask-migrate==3.1.0
    - flask-socketio==4.3.1
    - flask-sqlalchemy==2.4.4
    - flask-wtf==1.0.1
    - freetakserver==1.9.9.4
    - freetakserver-ui==1.9.9.2
    - geographiclib==1.52
    - geopy==2.2.0
    - greenlet==1.1.2
    - gunicorn==20.1.0
    - idna==3.3
    - importlib-metadata==4.11.3
    - importlib-resources==5.7.1
    - itsdangerous==2.0.1
    - jinja2==2.11.2
    - lxml==4.6.5
    - mako==1.2.0
    - markupsafe==2.0.1
    - monotonic==1.6
    - pathlib2==2.3.7.post1
    - pbr==5.8.1
    - pillow==9.1.0
    - protobuf==3.14.0
    - psutil==5.9.0
    - pycparser==2.21
    - pykml==0.2.0
    - pyopenssl==22.0.0
    - python-decouple==3.6
    - python-engineio==3.13.2
    - python-socketio==4.6.0
    - pyyaml==6.0
    - qrcode==7.3.1
    - requests==2.27.1
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.6
    - six==1.16.0
    - sqlalchemy==1.3.20
    - sqlalchemy-utils==0.38.2
    - tabulate==0.8.7
    - testresources==2.0.1
    - urllib3==1.26.9
    - werkzeug==2.0.3
    - wtforms==2.3.3
    - zipp==3.8.0
