---
dependencies:
  - { role: common }
  - { role: python3 }

galaxy_info:
  role_name: freetakserver
  author: freetakteam
  description: Free TAK Server
  license: license (EPL-2.0)
  min_ansible_version: '2.4'
  platforms:
    - name: Ubuntu
      versions:
        - {{ codename }}
        # - focal
  galaxy_tags:
    - freetakserver
    - tak
    - atak
